### ISSUE TITLE
oci cli commands fail with certificate error 'certificate verify failed'

### ISSUE THREAD

**Issue by puneethvelichala** [oracle/oci-cli#276]
I have installed CLI utility in our servers behind the proxy/firewall  , facing below issues related to certificate when running commands related to iam or object storage.

Any additional settings to be done to access OCI endpoints from a proxy.

$oci iam compartment list
RequestException: HTTPSConnectionPool(host='identity.us-ashburn-1.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/compartments?compartmentId=ocid1.tenancy.oc1..xxxxxxxxxxxxxx (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

oci os bucket list -ns ******** --compartment-id ocid1.compartment.oc1..********************************* 
RequestException: HTTPSConnectionPool(host='objectstorage.us-ashburn-1.oraclecloud.com', port=443): Max retries exceeded with url: /n/xxxxxxxxxxx/b?compartmentId=ocid1.compartment.oc1..************** (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by HamadaGabrIbrahim** [comment]
@puneethvelichala Thanks for reporting this.
This looks to be connection issue.
Can you access the URL from your computer?

**Comment by puneethvelichala** [comment]
@HamadaGabrIbrahim  This was resolved after adding the root certificate of the proxy and OCI to the OS default certificates list.
I had to use the global attribute --cert-bundle and pass the path to the cert file location while running the CLI , unfortunately I couldn't find any links to this issue until i figured out all the different possible options.

**Comment by hspuijbroek** [comment]
@puneethvelichala can you post an example off an oci cli command? I did an export from the https://console.eu-frankfurt-1.oraclecloud.com/ to get the certificate and imported this on the machine that has OCI CLI installed. After that i ran the following command to test the oci connection: 

oci compute instance get --instance-id (ocid id) --config-file (path to config)

I still received an error. So how did you solve this? 

Thanks! Regards, Hilbert

**Comment by kernleee** [comment]
@hspuijbroek Do you mean to pass in a --cert-bundle? Also if you are running CLI from a compute instance it might be easier for you to be using instance principals. https://www.ateam-oracle.com/calling-oci-cli-using-instance-principal

**Comment by kernleee** [comment]
I'll be closing this as @puneethvelichala had their issue resolved and @hspuijbroek has not responded. Feel free to reopen this issue if the issue persists.
