### ISSUE TITLE
Unable to install on my Mac due to SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by sachin-pikle** [oracle/oci-cli#65]
Here's the exception ... 

-- Downloading virtualenv package from https://github.com/pypa/virtualenv/archive/15.0.0.tar.gz.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/folders/2k/ssrhhylx4xd2pdwvhb9vwh2h0000gn/T/oci_cli_install_tmp_XXXX.1ZYU5Y4T", line 133, in create_virtualenv
    response = urlopen(VIRTUALENV_DOWNLOAD_URL)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>
ERROR: Failed to download virtualenv package. Please check that your trusted certificates are up to date and include the certificates necessary to verify github.com

**Comment by nathan-vu** [comment]
Apologies for the delayed response here. I suspect that you're running into the issue described here: https://bugs.python.org/issue28150

If you run the script as described in the linked bug report and then try to install the CLI again, does that work?

**Comment by smak-oracle** [comment]
Did you have a chance to try Nathan's suggestion? If we dont heard back from you, we will close this issue.

**Comment by viralmodi** [comment]
Hi Sachin,
I am assuming that Nathan's suggestion worked for you. Since there is no response for quite some time now, I will close this issue. If you are still seeing the issue, please re-open it.

**Comment by jrsmiley** [comment]
FYI - running the script described in the 3.6 readme fixed this issue for me

**Comment by monktastic** [comment]
So that others don't have to wade through that thread, the command in question is:

`/Applications/Python\ 3.6/Install\ Certificates.command`

And the relevant text is:

> This variant of Python 3.6 now includes its own private copy of OpenSSL 1.0.2.  Unlike previous releases, the deprecated Apple-supplied OpenSSL libraries are no longer used.  This also means that the trust certificates in system and user keychains managed by the Keychain Access application and the security command line utility are no longer used as defaults by the Python ssl module.  For 3.6.0b1, a sample command script is included in /Applications/Python 3.6 to install a curated bundle of default root certificates from the third-party certifi package (https://pypi.python.org/pypi/certifi).  If you choose to use certifi, you should consider subscribing to the project's email update service to be notified when the certificate bundle is updated.

**Comment by maheshwaria** [comment]
Thanks same issue seen with Python 3.7 and fixed by /Applications/Python\ 3.7/Install\ Certificates.command

**Comment by streamnsight** [comment]
FYI, I had to create the folder `/usr/local/etc/openssl@1.1` for the script to work.
Also had to make sure it was using the version of Python that I set as default (when using pyenv)

**Comment by jkremser** [comment]
With newer versions of Pythons(`3.7.3`) and MacOSes(`10.15.2`), the path `/Applications/Python\ 3.6/Install\ Certificates.command` no longer exist..

`brew reinstall openssl` fixed the issue for me

**Comment by leonjia0112** [comment]
> With newer versions of Pythons(`3.7.3`) and MacOSes(`10.15.2`), the path `/Applications/Python\ 3.6/Install\ Certificates.command` no longer exist..
> 
> `brew reinstall openssl` fixed the issue for me

I have the same python and macos version which the same issue. But
`brew reinstall openssl` didn't fix that for me.

**Comment by jkremser** [comment]
@leonjia0112 I also did `pip3 install certifi` but w/o the `brew reinstall openssl` step, it didn't work.

**Comment by vish1** [comment]
OCI CLI is now available on [Homebrew](https://formulae.brew.sh/formula/oci-cli)
